#!/bin/bash

# Quit Vivaldi
osascript -e 'quit app "Vivaldi.app"'

# Find path to Framework folder of current version and save it as variable
findPath="$(find /Applications/Vivaldi.app -name Vivaldi\ Framework.framework)"

# Copy custom yb_address_baresktop/VivaldiModpack/moddings/color_tabs.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/monochrome-icons.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/import-export-command-chains.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/chroma.min.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/easy-files.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/element-capture.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/global-media-controls.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/yb_address_bar.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/AdaptiveWebPanelHeaders.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/vivaldi-dashboard-camo.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/autoHidePanel_personal.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/feedIcon.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/mdNotes.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/ClearTabs.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/TidyTabs.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/dialogTab.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/moddings/ImmersiveAddressbar.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/SuperPins.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/TidyDownloads.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/TidyTitles.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/Vividly.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/ClickAddBlockList.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/colorful_loading_top_bar.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/moddings/moreFuncInWebPanel.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/moddings/widgets.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/moddings/yb_address_bar.js "$findPath"/Resources/vivaldi/

########################################################################################################################
cp /Users/acid/Desktop/VivaldiModpack/moddings/Follower-Tabs.js "$findPath"/Resources/vivaldi/user_files
cp /Users/acid/Desktop/VivaldiModpack/moddings/Picture-in-Picture.js "$findPath"/Resources/vivaldi/components/picture-in-picture

# Save path to browser.html as variable
browserHtml="$findPath"/Resources/vivaldi/window.html

# Backup original file
cp "$browserHtml" "$browserHtml".bak

# Insert references, if not present, and save to temporary file
sed -i '' -e '/<body>/,/<\/body>/ {
    /<body>/!{
        /<\/body>/!d
    }
}' "$browserHtml"

sed -i '' -e '/<\/body>/i\
<script src="color_tabs.js"></script>\
<script src="monochrome-icons.js"></script>\
<script src="import-export-command-chains.js"></script>\
<script src="chroma.min.js"></script>\
<script src="easy-files.js"></script>\
<script src="element-capture.js"></script>\
<script src="global-media-controls.js"></script>\
<script src="AdaptiveWebPanelHeaders.js"></script>\
<script src="vivaldi-dashboard-camo.js"></script>\
<script src="autoHidePanel_personal.js"></script>\
<script src="feedIcon.js"></script>\
<script src="mdNotes.js"></script>\
<script src="yb_address_bar.js"></script>\
<script src="ClearTabs.js"></script>\
<script src="TidyTabs.js"></script>\
<script src="dialogTab.js"></script>\
<script src="ImmersiveAddressbar.js"></script>\
' "$browserHtml"

#<script src="daily-wrap.js"></script>\
#<script src="SuperPins.js"></script>\
#<script src="Vividly.js"></script>\
#<script src="TidyDownloads.js"></script>\
#<script src="TidyTitles.js"></script>\
#<script src="ClickAddBlockList.js"></script>\
#<script src="colorful_loading_top_bar.js"></script>\

# Pause script
read -rsp $'Press [Enter] to restart Vivaldi...\n'

# Open custom files in text editor
# open "$findPath"/Resources/vivaldi/style/custom.css
# open "$findPath"/Resources/vivaldi/custom.js

# Open Vivaldi
open /Applications/Vivaldi.app --args --debug-packed-apps --silent-debugger-extension-api
# open /Applications/Vivaldi.app
